
function MiNombreFuncion() {
    document.writeln("<!DOCTYPE html1>");
    document.writeln("<html lang=\"es\">");
    document.writeln("<head>");
    document.writeln("    <meta charset=\"UTF-8\">");
    document.writeln("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
    document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
    document.writeln("    <title>Acerca de</title>");
    document.writeln("    <link rel=\"stylesheet\" href=\"css/about.css\" href=\"css/styles.css\">");
    document.writeln("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\"");
    document.writeln("        integrity=\"sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU\" crossorigin=\"anonymous\">");
    document.writeln("    <script src=\"https://kit.fontawesome.com/5c12f6cddc.js\" crossorigin=\"anonymous\"></script>");
    document.writeln("    <header>");
    document.writeln("        <div class=\"container-fluid\">");
    document.writeln("            <div class=\"row\">");
    document.writeln("                <div class=\"col-12 col-md-3 col-xl-4\">");
    document.writeln("                    <h1>");
    document.writeln("                        Jacket Store");
    document.writeln("                    </h1>");
    document.writeln("                </div>");
    document.writeln("                <div class=\"col-12 col-md-6 col-xl-4\">");
    document.writeln("                    <ul class=\"nav\">");
    document.writeln("                        <li class=\"nav-item col-2\">");
    document.writeln("                            <a class=\"nav-link active\" aria-current=\"page\" href=\"index.html\">Inicio</a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\"nav-item col-3\">");
    document.writeln("                            <a class=\"nav-link active\" aria-current=\"page\" href=\"about.html\">Nosotros</a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\"nav-item col-2\">");
    document.writeln("                            <a class=\"nav-link\" href=\"men.html\">Hombres</a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\"nav-item col-3\">");
    document.writeln("                            <a class=\"nav-link\" href=\"women.html\">Mujeres</a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\"nav-item col-2\">");
    document.writeln("                            <a class=\"nav-link\" href=\"kids.html\">Niños</a>");
    document.writeln("                        </li>");
    document.writeln("                    </ul>");
    document.writeln("                </div>");
    document.writeln("                <div class=\"col-3 col-md-3 col-xl-4\">");
    document.writeln("                    <ul class=\"nav\">");
    document.writeln("                        <li class=\"nav-item col-10\">");
    document.writeln("                            <a class=\"nav-link active\" href=\"login.html\" style=\"text-align: right;\">Iniciar Sesión</a>");
    document.writeln("                        </li>");
    document.writeln("                        <li class=\"nav-item col-2\">");
    document.writeln("                            <a class=\"nav-link active\" href=\"carrito.html\">");
    document.writeln("                                <i class=\"customicon fas fa-cart-arrow-down\"></i>");
    document.writeln("                            </a>");
    document.writeln("                        </li>");
    document.writeln("                    </ul>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("        </div>");
    document.writeln("        <div>");
    document.writeln("        </div>");
    document.writeln("    </header>");
    document.writeln("</head>");
    document.writeln("<body class=\"background\" background=\"imagenes/acercade1.webp\">");
    document.writeln("    <center>");
    document.writeln("        <h1 class=\" about\"> Acerca de nosotros</h1>");
    document.writeln("    </center>");
    document.writeln("    <hr />");
    document.writeln("    <h2 class=\"subabout\">Que nos hace diferentes?</h2>");
    document.writeln("    <center>");
    document.writeln("        <div class=\"boxdesign\">");
    document.writeln("            <div class=\"box1about\">");
    document.writeln("                <h3>Nuestra Historia</h3>");
    document.writeln("                <p>Somos una empresa que pretende impulsar un mercado que esta en demanda pero de una");
    document.writeln("                    forma mas especializada hace el diseño y la atencaion al cliente</p>");
    document.writeln("            </div>");
    document.writeln("            <div class=\"box2about\">");
    document.writeln("                <h3>Nuestro equipo</h3>");
    document.writeln("                <p>Estamos conformado por un equipo de 3 miembros que estaran siempre a la disposicion del cliente");
    document.writeln("                </p>");
    document.writeln("            </div>");
    document.writeln("            <div class=\"box3about\">");
    document.writeln("                <h3>Nuestra Mision</h3>");
    document.writeln("                <p>lo facil que es hacer un trabajo cuando amas lo que haces. es por esto que queremos </p>");
    document.writeln("            </div>");
    document.writeln("            <div class=\"boxdesign1\">");
    document.writeln("                <div class=\"box4about\">");
    document.writeln("                    <h3>Nuestra Experiencias</h3>");
    document.writeln("                    <p>Hemos experimento en este proceso de crecimento empresarial el apoyo incodicional de los amantes");
    document.writeln("                        a las chaquetas, especialmente aquellas personas que les gustan un diseño unico </p>");
    document.writeln("                </div>");
    document.writeln("                <div class=\"box5about\">");
    document.writeln("                    <h3>Clientes Satisfechos</h3>");
    document.writeln("                    <p>en cada chaqueta ponemos un gran esfuerzo para que cada cliente quede completamente satifechos");
    document.writeln("                        con su chaqueta </p>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("            <div class=\"phoadres\">");
    document.writeln("                <div class=\"adress\">");
    document.writeln("                    <p>Direccion Cll 127 # 7- 90 Usaquen</p>");
    document.writeln("                </div>");
    document.writeln("                <div class=\"phone\">");
    document.writeln("                    <p>TEL 3218405777</p>");
    document.writeln("                </div>");
    document.writeln("            </div>");
    document.writeln("        </div>");
    document.writeln("        </div>");
    document.writeln("    </center>");
    document.writeln("    <br /><br />");
    document.writeln("    ");
    document.writeln("</body>");
    document.writeln("<footer>");
    document.writeln("    <div>");
    document.writeln("        <center>");
    document.writeln("            <a href=\"https://www.facebook.com/\">");
    document.writeln("                <i class=\"customicon fab fa-facebook\"></i>");
    document.writeln("            </a>");
    document.writeln("            <a href=\"https://www.instagram.com/\">");
    document.writeln("                <i class=\"customicon fab fa-instagram\"></i>");
    document.writeln("            </a>");
    document.writeln("            <a href=\"https://www.twitter.com/\">");
    document.writeln("                <i class=\"customicon fab fa-twitter\"></i>");
    document.writeln("            </a>");
    document.writeln("        </center>");
    document.writeln("    </div>");
    document.writeln("</footer>");
    document.writeln("</html>");
}
//-->